# Nombre de la aplicación (Opcional)
spring.application.name=gestion-hospitalaria

# --- Configuración de la Base de Datos MySQL ---
# URL de conexión: apunta a tu servidor MySQL local (localhost:3306) y a la base de datos "tecsup"
# ASEGÚRATE DE HABER CREADO ESTA BASE DE DATOS EN MYSQL ANTES DE INICIAR.
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db

spring.datasource.username=root
# Coloca tu contraseña de MySQL aquí si tienes una. Si no, déjala en blanco.
spring.datasource.password=

# --- Configuración de JPA/Hibernate ---
# Muestra en la consola el código SQL que Hibernate ejecuta. ¡Muy útil para depurar!
spring.jpa.show-sql=true
# Dialecto específico para MySQL 8
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Esta es la línea más importante. 'update' es la mejor opción para desarrollar:
# Si las tablas no existen, las crea. Si cambias tus clases Java, intenta actualizar las tablas sin borrar datos.
spring.jpa.hibernate.ddl-auto=update

# --- Configuración del Puerto del Servidor ---
# Define que nuestra aplicación correrá en el puerto 8086
server.port=8086